services:
  - type: web
    name: heartplanning
    repo: github.com/AndersKringo/heartplanning
    branch: main
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATA_DIR
        value: /data
    disk:
      name: schedule-data
      mountPath: /data
      sizeGB: 1
